### ISSUE TITLE
Fix inserting incidents into the database

### ISSUE THREAD

**Issue by FarihaChoudhury** [Zhi-704/Railway-Tracker#102]
### Task

- [x] Correct transform_national.py to populate end and start dates if not given from the NationalRail API, to ensure all incidents are being inserted into the database.
- [x] If no ```incident_end``` date is given, use ```incident_start``` date.
- [x] If no ```incident_start``` date then use ```creation_time```. 
- [x] Allow nullable on columns ````is_planned```, ```incident_summary```, ```incident_description```, ```incident_uri```, ```affected_routes```. Use ALTER TABLE COLUMN. 

### User Story
As a developer, I must make sure all incidents are inserted into the database to ensure that users are notified for alerts accurately.
