### ISSUE TITLE
Connect Report pipeline as a lambda

### ISSUE THREAD

**Issue by FarihaChoudhury** [Zhi-704/Railway-Tracker#106]
### Task

Call ETL in pdf_report.py: 
- [x] Call extract performance of stations from RDS, 
- [x] Call transform into graphs 
- [x] Call load into S3 bucket and send as email to subscribers
- [x] Make it a lambda function 
- [x] Create docker file 

### User Story
As a developer, I want to create a lambda function to call ETL and generate a report, so that users can view the report.
