### ISSUE TITLE
Ensure all ReadMes are up to date

### ISSUE THREAD

**Issue by Zhi-704** [Zhi-704/Railway-Tracker#108]
### Task
- [x] Update archive readme
- [x] Update dashboard readme
- [x] Update database readme
- [x] Update national_rail readme
- [x] Update pdf_report readme
- [x] Update realtime_trains readme
- [x] Update terraform readme

### User Story
As a developer, I want to ensure all documentation is kept up to date so that if I ever come back to the project I understand what files are for what functionality.
