### ISSUE TITLE
Add Entity Relationship Diagram

### ISSUE THREAD

**Issue by A-Faris** [Zhi-704/Railway-Tracker#11]
### Task

- [x] Create and design ERD
- [x] Make any changes following feedback
- [x] Get approval
- [x] Add ERD to repo

### User Story

As a developer, I want to view the ERD so I can understand how the data is stored in the database
