### ISSUE TITLE
Create github actions

### ISSUE THREAD

**Issue by Zhi-704** [Zhi-704/Railway-Tracker#2]
### Task

- [x] Create yaml file for automated testing for all test files
- [x] Ensure it fails if not all tests pass
- [x] Create yaml file for automated linting for all python files
- [x] Ensure it fails if pylint score is below 8 for any files

### User Story
As a developer, I want to automate testing and linting the repository so that less time is wasted on ensuring code quality is high and minimises the chance that bugs are introduced in the main repository.
