### ISSUE TITLE
dashboard: main page

### ISSUE THREAD

**Issue by fm1psy** [Zhi-704/Railway-Tracker#28]
The main page will include statistics and figures that adhere to the requirements set by the team.

### Task
- [x] add % of trains cancelled
- [x] % of trains delayed by 5 minutes.
- [x] Average delay across all trains and average delay across all trains delayed >1 minute
- [x] highest overall delay
- [x] make comparisons of today's data to the previous day
- [x] add seven day rolling averages
- [x] add other statistics of interest (mention in the PR)

### User Story
As a user, I want to use this railway tracker to get key insights, such as percentage of journeys cancelled or delayed over 5 minutes. This and other results could help me see how efficient the railway system is.
