### ISSUE TITLE
report: create report script

### ISSUE THREAD

**Issue by fm1psy** [Zhi-704/Railway-Tracker#31]
### Task

- [x] create a script that generates a summary report based on the data shown in the dashboard
- [x] structure the pdf in a digestible and appealing manner
- [x] save this pdf in an S3 bucket

### User Story

as a developer, this script is necessary to ensure users receive their summaries
