### ISSUE TITLE
dashboard: create train alert script

### ISSUE THREAD

**Issue by fm1psy** [Zhi-704/Railway-Tracker#34]
### Task
- [ ] create a script that iterates through every subscription to the train alerts
- [ ] get the most recent data and look for any matches i.e. incident matches what the user subscribed to
- [ ] when there is a match, send an email/SMS

### User Story
I need this script as a developer to make sure users receive their alerts on time
