### ISSUE TITLE
Seed the database 

### ISSUE THREAD

**Issue by FarihaChoudhury** [Zhi-704/Railway-Tracker#36]
### Task

- [x] Seed database with operators 
- [x] Seed database with stations
- [x] Seed database with cancellation codes

### User story

As a developer, I want to seed the database with initial data so that the database is populated with known information.
