### ISSUE TITLE
dashboard: add readme

### ISSUE THREAD

**Issue by fm1psy** [Zhi-704/Railway-Tracker#41]
### Task
- [x] add overview to the dashboard
- [x] add details on the installation
- [x] add details on the setup

### User Story
I need a readme as a developer so that I can understand how the system is supposed to work and how I can use the code written.
