### ISSUE TITLE
Update Schema

### ISSUE THREAD

**Issue by FarihaChoudhury** [Zhi-704/Railway-Tracker#64]
### Task

- [x] Update datatypes in the waypoint table: run_date to type Date
- [x] Include constraint on waypoints arrival and departure times.
- [x] Delete London station from database
- [x] Fix mismatch in FKs
- [x] Fix constraint on cancel code

### User story
As a developer I want to update the schema to ensure the schema is representative of the data we pull from the API, allowing insertions to the database to occur seamlessly.
