### ISSUE TITLE
Add Architecture Diagram

### ISSUE THREAD

**Issue by A-Faris** [Zhi-704/Railway-Tracker#7]
### Task

- [x] Create and design Architecture Diagram
- [x] Make any changes following feedback
- [x] Get approval
- [x] Add Architecture Diagram

### User Story

As a developer, I want to be able to see the diagrams so I can understand the code logic
