### ISSUE TITLE
Test Archiving Data

### ISSUE THREAD

**Issue by FarihaChoudhury** [Zhi-704/Railway-Tracker#79]
### Task

- [x] Test archive.py
- [x] Test clean_national_rail.py
- [x] Test clean_real_time_trains.py
- [x] Test db_connection.py

### User Story
As a developer, I want to test that the functionality of Archive works as expected and reduces the chances of bugs to occur in the future.
