### ISSUE TITLE
Terraform Dashboard

### ISSUE THREAD

**Issue by FarihaChoudhury** [Zhi-704/Railway-Tracker#90]
### Task

- [x] Dockerfile for dashboard
- [x] Upload image to ECR
- [x] Create an ECS fargate service to run the dashboard with terraform
- [x] Update README 

### User Story
As a developer, I want to automate the process of deploying a dashboard to an ECS service on AWS so that I can maintain and repeat this process if need be.
