### ISSUE TITLE
Remove random code from SNS functions

### ISSUE THREAD

**Issue by FarihaChoudhury** [Zhi-704/Railway-Tracker#94]
### Task:

- [x] Delete ```get_data_from_json()``` function
- [x] Use same quotation marks for docstrings
- [x] Add docstrings to functions that are missing docstrings 

### User Story:
As a developer, I want to keep my code consistent and clean so that it is easy to understand and for other developers to work on top of.
